services:
  - type: web
    name: ceelosol-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NPM_CONFIG_PRODUCTION
        value: false
