services:
  - type: web
    name: ceelosol-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: REACT_APP_BACKEND_URL
        value: https://ceelosol-backend.onrender.com
